api_keys:
  tradingview: ''
  cryptorank: ''
  whale_alert: ''
  binance: ''

monitoring:
  pairs:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
    - BNBUSDT
    - ADAUSDT
  timeframes:
    - 1h
    - 4h
    - 1d
  volume_threshold: 1000000  # Объем в USD для отслеживания
  whale_threshold: 500000    # Размер транзакции для отслеживания китов

signals:
  enabled: true
  channel_id: null  # ID канала для отправки сигналов
  include_charts: true
  notification_cooldown: 3600  # Время между уведомлениями в секундах

smart_money:
  oi_change_threshold: 5      # % изменения Open Interest
  funding_rate_threshold: 0.1  # % Funding Rate для сигнала
  liquidity_zones: true        # Отслеживать зоны ликвидности
  order_blocks: true           # Отслеживать блоки ордеров