dbscan:
  default_eps: 0.002
  volatility_adjust: true

risk_management:
  atr_period: 14
  tp1_multiplier: 1.5
  tp2_multiplier: 3.0
  stop_multiplier: 1.0

confidence:
  volume_weight: 0.4
  rsi_weight: 0.3
  density_weight: 0.3